### ISSUE TITLE
With certain photos, Photo2Shape makes QGIS crash

### ISSUE THREAD

**Issue by dgoedkoop** [alexbruy/photo2shape#3] opened 2016-11-04 12:47 UTC
We have an Olympus TG-870 camera with GPS. When trying to process its photos with the Photo2Shape plugin, it crashes (and the entire QGIS application crashes when this happens).

**Comment by alexbruy** [comment] 2017-04-06 14:15
Can you provide sample photo, so I can debug this issue?

**Comment by m-kuhn** [comment] 2017-06-19 12:33
I had a crash with the plugin today but couldn't reproduce it after

 * first time executed it with "append" checked but a new file (crash, minidump...)
 * second time executed it without "append". At some point it stopped but the warning didn't make it to the screen (missing attribute for `QgsMessageBar.pushMessage()`)
 * third time executed it without "append" (and qgis2compat removed, was guessing that the above exception might have been qgis2compats fault), the shp already existed and was successfully imported.
 * tried again a new file with "append" checked, got an exception now, but no more crash:

    photoimporter.py: 127 in importPhotos
      ft['filepath']  = fName
    KeyError: 'filepath'

**Comment by dgoedkoop** [comment] 2017-06-20 07:50
@alexbruy Sorry, I missed that message. Here is an example photo!
![photo](https://user-images.githubusercontent.com/7602407/27322149-3ed8d762-559d-11e7-9a10-b6504cfb6fd0.jpg)

**Comment by m-kuhn** [comment] 2017-06-20 09:50
I noticed that Qgis crashes if an exception is raised in the importer.

Can yiu try this to find out why an exception is raised?

https://gis.stackexchange.com/a/148353

**Comment by alexbruy** [comment] 2017-07-21 05:42
Should be fixed now

**Closed by alexbruy** 2017-07-21 05:42 UTC
Labels: bug
